apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: ai-sre-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
        - name: checkout-service
          image: nginx:1.25
          ports:
            - containerPort: 80
